# Ignore branches testing third-party CI environments.
branches:
  except:
    - circleci
    - travisci

install:
  - ps: choco install -y -r swig --version 3.0.9
  - ps: choco install -y -r ruby
  - ps: refreshenv

before_build:
  - cmake -G "Visual Studio 14 2015 Win64" -DTINYSPLINE_WITH_PYTHON=OFF .

build:
  project: tinyspline.sln
